project:
  type: website

website:
  title: "Open Research Conversation - Open Scholarship Communities"
  site-url: https://ns-rse.github.io/open-research-conversation-2023-11
  description: "Slides for a talk at University of Sheffield Open Research Conversation 2023-11-29"
